const config = require('./utils/config')
const express = require('express')
const app = express()
const cors = require('cors')
const registerRouter = require('./controllers/register')
const loginRouter = require('./controllers/login')
const giverRouter = require('./controllers/giver')
const ownerRouter = require('./controllers/owner')
const petRouter = require('./controllers/pet')
const mongoose = require('mongoose')
mongoose.connect(config.MONGO_URI)

app.use(cors())
app.use(express.json())
app.use('/api/register', registerRouter)
app.use('/api/login', loginRouter)
app.use('/api/giver', giverRouter)
app.use('/api/owner', ownerRouter)
app.use('/api/pet', petRouter)

module.exports = app